// 由 scripts/generate-pinyin.mjs 生成，请勿手工编辑。
export const pinyinInitialsById = {
  "moisture-001": "tmzsbns bns zsj",
  "moisture-002": "gy",
  "moisture-003": "sjxa xbjzz",
  "moisture-004": "jsw",
  "moisture-005": "fc wss",
  "whitening-001": "yxa wss",
  "whitening-002": "wsskhxs zx khxs",
  "whitening-003": "xgg",
  "whitening-004": "cms nxs ajhs",
  "whitening-005": "qs",
  "antiaging-001": "shcc wss wc",
  "antiaging-002": "st dt",
  "antiaging-003": "bsy",
  "antiaging-004": "jmtqw eljm",
  "antiaging-005": "xqs",
  "acne-001": "sys qjs",
  "acne-002": "gs qjs gcs rs",
  "acne-003": "res",
  "acne-004": "csjy",
  "repair-001": "jxc qjjxcg",
  "repair-002": "lh",
  "repair-003": "nns",
  "repair-004": "gt",
  "safety-001": "ybtebjt ebjt fsj",
  "safety-002": "eyhtyhx wlfs kwfs",
  "safety-003": "tpzjs dsms js lbts",
  "safety-004": "nbjz dqjbjsz qbjz qbyz qbbz qbdz",
  "safety-005": "jjyszlt jjlyszlt",
  "whitening-006": "byjjbef",
  "whitening-007": "aws",
  "repair-005": "eljmfjcwrbcw eljm",
  "antiaging-006": "kfy",
  "acne-005": "xxsys",
  "sunscreen-001": "akll hxfs",
  "sunscreen-002": "afbz djjyjebjxjjw",
  "safety-006": "ycjj jj",
  "safety-007": "xj xl",
  "safety-008": "byyc",
  "acne-006": "nms",
  "acne-007": "blgtqw bldbm fl",
  "acne-008": "mgdbm",
  "moisture-006": "dec",
  "moisture-007": "wec",
  "moisture-008": "bec",
  "base-001": "ygxjasybz",
  "base-002": "qyjpqywhs",
  "base-003": "bxxabxxjejjnhsngjw gjw",
  "base-004": "xjsec",
  "base-005": "yslw ygslw",
  "base-006": "xjsecmtg",
  "base-007": "jslcz",
  "base-008": "yeaehpssn",
  "base-009": "jbxxjejjnhsa",
  "base-010": "sltysz sp",
  "base-011": "yhx eyhx",
  "base-012": "jyec",
  "base-013": "jgwjhgs",
  "moisture-009": "jec",
  "moisture-010": "hzt",
  "base-014": "jejjgywjljhw gyjhw",
  "safety-009": "dqjbyt xxt",
  "repair-006": "eljmfjcwly eljmly",
  "base-015": "bxxejjnhsasycjmjjbxszjljhw",
  "whitening-008": "lyjkhxs yjm yj",
  "antiaging-007": "jt",
  "whitening-009": "gggcgtqw ggcd",
  "whitening-010": "zgtqw",
  "repair-007": "ychhtqw",
  "repair-008": "hqgtqw hqg",
  "whitening-011": "sgtqw",
  "base-016": "en",
  "base-017": "qhbmy",
  "base-018": "nmsn",
  "base-019": "scgpy",
  "base-020": "yzxgasn",
  "base-021": "lzxdj llz",
  "base-022": "jwscsyjjsz",
  "base-023": "xjjjjgyw",
  "base-024": "syc esec",
  "base-025": "bxszlgjwn",
  "base-026": "qhjydx",
  "base-027": "llz",
  "antiaging-008": "shczlsz wsszlsz",
  "base-028": "jas",
  "base-029": "bxszlwcbxszjljhw kbmgjw",
  "whitening-012": "seyyjegchjwessz",
  "base-030": "jc",
  "moisture-011": "hhbzy hhby",
  "antiaging-009": "zc",
  "antiaging-010": "shcbsz",
  "repair-009": "qjjxcg",
  "antiaging-011": "qjpntshsz",
  "base-031": "jwscsssdjqjqhrgsz",
  "repair-010": "qbjbxabjs",
  "moisture-012": "zbjcctqw klj",
  "moisture-013": "yzgtqw",
  "safety-010": "ygxjasyzysy",
  "antiaging-012": "sygzctqw",
  "moisture-014": "mjztqw",
  "repair-011": "sjfwjdb",
  "moisture-015": "hxzgztqw",
  "base-032": "xsgsgysz",
  "base-033": "kbm",
  "base-034": "jslcz",
  "base-035": "hyj",
  "safety-011": "dqjb",
  "base-036": "c",
  "base-037": "jyec",
  "base-038": "ymy",
  "base-039": "lz",
  "antiaging-013": "hlbs",
  "whitening-013": "khxszlsz",
  "cleanse-001": "ygclszn ygjlsn lsybh",
  "cleanse-002": "ygcjmlszn lsy eylh",
  "cleanse-003": "yyxabjtcj tcj",
  "cleanse-004": "yyxa eycxa",
  "cleanse-005": "ptglgjptg gjptg yyjptg wjtg",
  "cleanse-006": "yyxgasnbtlxbh yyxqyhszn yyxgasn",
  "cleanse-007": "gyjejjgyw ejjgy adgy hgyw",
  "cleanse-008": "jjay",
  "cleanse-009": "gejqbjsjjlha ylzgej",
  "cleanse-010": "blwx bdltx qx",
  "cleanse-011": "blktycay akd qx",
  "cleanse-012": "lmbz qx",
  "cleanse-013": "elhxmjytkzyyqx elhx mjy tkz yyqx",
  "cleanse-014": "bjsnslsj slsj bjsn",
  "cleanse-015": "ynxn jqsft",
  "cleanse-016": "yeceyzszzgj zgj"
};
